<?php

/**
 * @file
 * dccr_blocks.module
 */

/**
 * Implements hook_block_info().
 */
function dccr_blocks_block_info() {
  $blocks = array();
  $blocks['proposed_sessions_header'] = array(
    'info' => t('Proposed sessions list header.'),
  );
  $blocks['propose_sessions_link'] = array(
    'info' => t('Link to propose a session.'),
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function dccr_blocks_block_configure($delta = '') {
  $form = array();

  switch ($delta) {
    case 'proposed_sessions_header':
      $form['text_body'] = array(
        '#type' => 'text_format',
        '#title' => t('Enter the text here'),
        '#default_value' => variable_get('text_variable', ''),
      );
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function dccr_blocks_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'proposed_sessions_header':
      variable_set('text_variable', $edit['text_body']['value']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function dccr_blocks_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'proposed_sessions_header':
      $block['content'] = array(
        'title' => array(
          '#type' => 'markup',
          '#markup' => variable_get('title', ''),
        ),
        'message' => array(
          '#type' => 'markup',
          '#markup' => variable_get('text_variable', ''),
        ),
      );
      break;

    case 'propose_sessions_link':
      $block['content'] = array(
        'link' => array(
          'type' => 'markup',
          '#markup' => l(t('Propose a session!'), 'node/add/dccr-session'),
        ),
      );
      break;
  }

  return $block;
}
